labels: ["internal"]
body:
  - type: "checkboxes"
    id: "no-duplicates"
    attributes:
      label: "Please check for similar discussions first"
      options:
        - required: True
          label: "I [searched](https://github.com/nminaian/keithley_daq/discussions/categories/internal) and couldn't find an appropriate discussion to participate in instead."
  - type: "textarea"
    id: "description"
    validations:
      required: True
    attributes:
      label: "Description"
      description: "Please describe the internal matter. Please provide a few details as to how this matter might be handled."
