[build-system]
requires = ["flit_core==3.9.0"]
build-backend = "flit_core.buildapi"

[project]
name = "keithley_daq_docs"
version = "0.0.0"
description = "Docs."
dependencies = [
    # ? Core docs
    "docutils==0.21.2",
    "linkify-it-py==2.0.3",
    "myst-nb==1.1.0",
    "myst-parser==3.0.1",
    "numpydoc==1.7.0",
    "ruamel-yaml==0.18.6",
    "sphinx-autobuild==2024.4.16",
    "sphinx-autodoc2==0.5.0",
    "sphinx-book-theme==1.1.3",
    "sphinx-design==0.6.0",
    "sphinx-thebe==0.3.1",
    "sphinx-tippy==0.4.3",
    "sphinx-togglebutton==0.3.2",
    "sphinx==7.3.7",
    "sphinxcontrib-bibtex==2.6.2",
    "sphinxcontrib-mermaid==0.9.2",
    "sphinxcontrib-towncrier==0.4.0a0",
    # ? https://nvd.nist.gov/vuln/detail/CVE-2024-37891
    # ? via sphinx
    "urllib3>=2.2.2",
]

[tool.fawltydeps]
deps = ["docs/pyproject.toml"]
code = ["docs"]
ignore_undeclared = [
    "keithley_daq_docs",
    "keithley_daq_tests",
    "keithley_daq_tools",
    "keithley_daq",
]
ignore_unused = [
    # ? Core docs tools or declared as extensions in `conf.py`
    "linkify-it-py",
    "myst-nb",
    "myst-parser",
    "sphinx-autobuild",
    "sphinx-autodoc2",
    "sphinx-book-theme",
    "sphinx-design",
    "sphinx-thebe",
    "sphinx-tippy",
    "sphinx-togglebutton",
    "sphinxcontrib-bibtex",
    "sphinxcontrib-mermaid",
    "sphinxcontrib-towncrier",
    # ? https://nvd.nist.gov/vuln/detail/CVE-2024-37891
    # ? via sphinx
    "urllib3",
]
[tool.fawltydeps.custom_mapping]
ruamel-yaml = ["ruamel"]
